### ISSUE TITLE
surprising replay in development

### ISSUE THREAD

**Issue by mccraigmccraig** [onyx-platform/onyx-kafka#29]
onyx-0.9.9
onyx-kafka-0.9.9.0
kafka 0.9.0.1 & kafka 0.10.0.0

in development i am seeing messages replayed when onyx is restarted ( tools.ns reload, new environment with random onyx-id created, new job submitted )

in production processing correctly resumes after the last acknowledged message ( static onyx-id, job resumed )

here's my onyx-kafka task catalog entry - https://www.refheap.com/470754c4f1daab1e0f2610f71

if i force a reset then that seems to work ok - processing resumes at the largest offset as expected - so the problem appears to be related to reading the last acknowledged offset

**Comment by lbradstreet** [comment]
@mccraigmccraig sorry for the delay getting to this problem.

The problem here is that we have switched the checkpointing mechanism to use Onyx's internal zookeeper data management. The difference that you're seeing is that the checkpoint path is being namespaced by the tenancy-id.

I think this behaviour change is probably the wrong choice and we shouldn't be scoping in this way by default, as it's not how it operated before, and gives you no way to resume processing jobs on new tenancy ids.

I suggest we go back to the old behaviour, keyed differently, and still do the checkpointing ourselves. This will be less surprising for current users. Later we can then figure out a way to provide both ways.

cc @MichaelDrogalis

**Comment by mccraigmccraig** [comment]
@lbradstreet thanks for investigating lucas - that all seems to make sense

**Comment by MichaelDrogalis** [comment]
I agree - the change to scope by tenancy ID was unintentional on my part.

**Comment by lbradstreet** [comment]
Fixed in master. Thanks for the report @mccraigmccraig.
